apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: dataviz-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
      - name: init-backend
        image: busybox
        command: ['sh', '-c', 'echo "Prioritizing backend container" && sleep 10']
      containers:
      - name: backend
        image: ismailza/mern-stack-app-backend
        ports:
        - containerPort: 3000
        env:
        - name: APP_MODE
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: app_mode
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: DB_PASS
        volumeMounts:
        - name: shared-logs
          mountPath: /var/log/shared
      - name: sidecar-logger
        image: busybox
        command: ["/bin/sh", "-c"]
        args:
          - while true; do
              echo "$(date) - Application log entry" >> /var/log/shared/app.log;
              sleep 10;
            done
        volumeMounts:
        - name: shared-logs
          mountPath: /var/log/shared
      volumes:
      - name: shared-logs
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: dataviz-ns
spec:
  type: NodePort
  selector:
    app: backend
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30300 