apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: dataviz-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      initContainers:
      - name: init-frontend
        image: busybox
        command: ["/bin/sh", "-c"]
        args:
          - |
            cat <<EOF > /usr/share/nginx/html/index.html
            <!DOCTYPE html>
            <html>
            <head>
                <title>Data Visualization</title>
                <style>
                    body { font-family: Arial, sans-serif; margin: 0; padding: 20px; color: #333; }
                    h1 { color: #2c3e50; }
                    p { line-height: 1.6; }
                </style>
            </head>
            <body>
                <h1>Data Visualization Application</h1>
                <p>Welcome to our data visualization platform.</p>
            </body>
            </html>
            EOF
        volumeMounts:
        - name: app-storage
          mountPath: /usr/share/nginx/html
      containers:
      - name: frontend
        image: ismailza/mern-stack-app-frontend
        ports:
        - containerPort: 5173
        volumeMounts:
        - name: app-storage
          mountPath: /usr/share/nginx/html
      volumes:
      - name: app-storage
        persistentVolumeClaim:
          claimName: app-logs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: dataviz-ns
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - port: 5173
    targetPort: 5173
    nodePort: 30173 